enum ConfigKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    VERSION = 'VERSION',
    BASE_PATH = 'BASE_PATH',
    CORS_WHITELIST = 'CORS_WHITELIST',
    TIMEZONE_DEFAULT_NAME = 'TIMEZONE_DEFAULT_NAME',
    MONGO_DATABASE_CONNECTION_STRING = 'MONGO_DATABASE_CONNECTION_STRING',

    // Swagger
    SWAGGER_ENABLED = 'SWAGGER_ENABLED',
}

export default ConfigKey;
